token = "b4a61a763d96088fe2b48083d196f000000000000000078fe12634d942cc7485c2257092fd355a8bd0295" # Токен ?ооб?е??ва ??он?ак?е

buttons_text = "shuex"
message_text = "@all ?? " # Тек?? ?ооб?ени?. ??ли ко?о?е 4096 бай?ов - б?де? пов?о??н мак?имал?ное коли?е??во ?аз

logging_level = "DEBUG"
delay = 0.33
